// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKWLmPxDwQpAhORwj4J7bHqmhsbLImRsQ',
    appId: '1:946881961050:web:9d5d1fcf2f970da82d0c63',
    messagingSenderId: '946881961050',
    projectId: 'grade-calculator-e83f9',
    authDomain: 'grade-calculator-e83f9.firebaseapp.com',
    storageBucket: 'grade-calculator-e83f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7V3PXsd5Z7yCkusBz99SgHsiGUnL27XM',
    appId: '1:946881961050:android:4b62d3de21f2455f2d0c63',
    messagingSenderId: '946881961050',
    projectId: 'grade-calculator-e83f9',
    storageBucket: 'grade-calculator-e83f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDngmyznxdxqu3xJUBUmYLQfx0RoirnTMI',
    appId: '1:946881961050:ios:279d3f4c70116b132d0c63',
    messagingSenderId: '946881961050',
    projectId: 'grade-calculator-e83f9',
    storageBucket: 'grade-calculator-e83f9.firebasestorage.app',
    iosBundleId: 'com.example.gradecalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDngmyznxdxqu3xJUBUmYLQfx0RoirnTMI',
    appId: '1:946881961050:ios:279d3f4c70116b132d0c63',
    messagingSenderId: '946881961050',
    projectId: 'grade-calculator-e83f9',
    storageBucket: 'grade-calculator-e83f9.firebasestorage.app',
    iosBundleId: 'com.example.gradecalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKWLmPxDwQpAhORwj4J7bHqmhsbLImRsQ',
    appId: '1:946881961050:web:b54f09c04b91e8012d0c63',
    messagingSenderId: '946881961050',
    projectId: 'grade-calculator-e83f9',
    authDomain: 'grade-calculator-e83f9.firebaseapp.com',
    storageBucket: 'grade-calculator-e83f9.firebasestorage.app',
  );
}
